### ISSUE TITLE
Unable to run in x64 system

### ISSUE THREAD

**Issue by Peter-JY** [azuwis/pianotrans#12]
I can't open this application. 

> Exception in thread Thread-1:
> 
> Traceback (most recent call last):
>   File "threading.py", line 926, in _bootstrap_inner
>   File "threading.py", line 870, in run
>   File "PianoTrans.py", line 26, in worker
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "torch\__init__.py", line 124, in <module>
>     raise err
> OSError: [WinError 193] %1 不是有效的 Win32 应用程序。 Error loading "D:\Peter\PianoTrans\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

I've already installed C++, because I've used it to write an spall application.

System info:
版本	Windows 10 专业版
版本号	21H2
安装日期	‎2022/‎3/‎19
操作系统内部版本	19044.1645
体验	Windows Feature Experience Pack 120.2212.4170.0

**Comment by azuwis** [comment]
看起来像是 https://github.com/pytorch/pytorch/issues/46592#issuecomment-712958720

或者 https://github.com/azuwis/pianotrans/issues/3

**Comment by azuwis** [comment]
Closing due to lack of activity, feel free to reopen if still have problem.
